<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>arith</AssemblyName>
    <RootNamespace>Arith</RootNamespace>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Arith.Cli.Tests" />
  </ItemGroup>
</Project>
